#include <stdio.h>
#include <stdlib.h>
#include <resolv.h>
#include <errno.h>
#include <string.h>
#include <sys/time.h>
#include <sys/resource.h>
#include <unistd.h>
#include <sys/select.h>
#include <sys/socket.h>
#include <sys/resource.h>
#include <arpa/inet.h>
#include <termios.h>
#include <signal.h>
#include <curl/multi.h>
